# fly.toml app configuration file generated for irc-skat-bot on 2026-04-08T07:21:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'irc-skat-bot'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9180
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
